# Stage 1: build
FROM node:20-alpine AS build

WORKDIR /app

# copiar dependencias
COPY package.json pnpm-lock.yaml ./

RUN corepack enable
RUN pnpm install --frozen-lockfile --prod=false

# copiar código
COPY . .

# Variable de entorno de Vite inyectada en build
ARG VITE_API_BASE_URL=http://localhost:8080
ARG VITE_PYTHON_SERVICE_URL=http://localhost:8000
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_PYTHON_SERVICE_URL=$VITE_PYTHON_SERVICE_URL

# build de producción
RUN pnpm run build


# Stage 2: servir con nginx
FROM nginx:alpine

# eliminar configuración default
RUN rm -rf /usr/share/nginx/html/*

# copiar build
COPY --from=build /app/dist /usr/share/nginx/html

# exponer puerto
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
