export const MAP_CONSTANTS = {
  caldasCenter: {
    lat: 5.2983,
    lng: -75.2479,
  },
  defaultZoom: 8,
  minZoom: 7,
  maxZoom: 16,
  defaultZoneRadiusMeters: 500,
  maxZoneRadiusMeters: 500,
  minDetections: 1,
  maxDetections: 16,
  caldasHighlightRadiusMeters: 64000,
  liveWindowMinutes: 10,
  highActivityThreshold: 10,
  mediumActivityThreshold: 4,
  maxSpeciesInPopup: 5,
  birdPointMinDistanceMeters: 45,
  birdPointPlacementAttemptsMultiplier: 24,
  birdPointRadiusPixels: 4,
  birdPointColor: '#b5161b',
  birdPointFillOpacity: 0.46,
  caldasHighlightColor: '#c1121f',
  caldasHighlightFillOpacity: 0.03,
  mockRefreshIntervalMs: 8000,
  positronTileUrl: 'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',
  positronAttribution: '&copy; OpenStreetMap contributors &copy; CARTO',
  osmTileUrl: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
  osmAttribution: '&copy; OpenStreetMap contributors',
} as const
