export const MAP_LABELS = {
  activeZone: 'Zona activa',
  lowActivity: 'Baja',
  mediumActivity: 'Media',
  highActivity: 'Alta',
  liveActivity: 'Actividad en vivo',
  caldasRegion: 'Caldas',
  centerOnCaldas: 'Centrar en Caldas',
  birdPointsLegend: 'Pajaros detectados',
  lastDetection: 'Ultima deteccion',
  detectedSpecies: 'Especies detectadas',
  appearanceFrequency: 'Frecuencia de aparicion',
  totalDetections: 'Detecciones',
  viewCamera: 'Ver camara',
  noRecentActivity: 'Sin actividad reciente',
  unknownDate: 'Sin registro reciente',
  mapLoadError: 'No fue posible cargar el mapa de actividad.',
  mapNoData: 'No hay actividad reciente registrada.',
  mapLoadingAria: 'Cargando mapa de actividad',
  mapCenterControlAria: 'Control para centrar en Caldas',
  speciesDetectedCountSuffix: 'especies detectadas',
  locationSeparator: ' - ',
  relativeLessThanMinute: 'hace menos de 1 min',
  relativeMinutesSuffix: 'min',
  relativeHoursSuffix: 'h',
  relativeDaysSuffix: 'd',
} as const
