CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS USERS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS PHOTOS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    BASE64 TEXT NOT NULL,
    TAKEN_AT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS SPECIES (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    POPULAR_NAME VARCHAR(255) NOT NULL UNIQUE,
    SCIENTIFIC_NAME VARCHAR(255) NOT NULL UNIQUE,
    YOLO_LABEL VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS CAMARAS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    NAME VARCHAR(255) NOT NULL UNIQUE,
    ANGLE_XY DECIMAL(5, 2) NOT NULL,
    ANGLE_XZ DECIMAL(5, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS LOCATIONS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    REGION VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    LATITUDE DECIMAL(10, 8) NOT NULL,
    LONGITUDE DECIMAL(11, 8) NOT NULL,
    HEIGHT DECIMAL(5, 2) NOT NULL,
    CAMERA_ID UUID NOT NULL UNIQUE,
    FOREIGN KEY (CAMERA_ID) REFERENCES CAMARAS(ID)
);

CREATE TABLE IF NOT EXISTS BIRDS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    PROBABILITY_YOLO DECIMAL(5, 2) NOT NULL,
    SPECIES_ID UUID NOT NULL,
    PHOTO_ID UUID NOT NULL,
    CAMERA_ID UUID NOT NULL,
    FOREIGN KEY (SPECIES_ID) REFERENCES SPECIES(ID),
    FOREIGN KEY (PHOTO_ID) REFERENCES PHOTOS(ID),
    FOREIGN KEY (CAMERA_ID) REFERENCES CAMARAS(ID)
);
