export const labels = {
  appTitle: 'STDC',
  homePageTitle: 'Inicio | STDC',
  homeLoaderAria: 'Cargando contenido de inicio',
  settingsPageTitle: 'Ajustes | STDC',
  settingsLoaderAria: 'Cargando contenido de ajustes',
  settingsHeading: 'Ajustes de cuenta',
  settingsProfileTitle: 'Información del usuario',
  settingsUsernameLabel: 'Usuario',
  settingsRoleLabel: 'Rol',
  settingsActionsTitle: 'Sesión',
  settingsLogoutButton: 'Cerrar sesión',
  roleAdministrator: 'Administrador',
  roleTourGuide: 'Guía turístico',
  authSessionExpired: 'Tu sesión expiró. Inicia sesión de nuevo',
  camerasPageTitle: 'Camaras | STDC',
  camerasLoaderAria: 'Cargando contenido de camaras',
  camerasManagementTitle: 'Gestión de cámaras',
  camerasAdminDescription: 'Puedes crear, editar o eliminar cámaras desde esta sección',
  camerasGuideDescription: 'Puedes visualizar cámaras, pero solo ADMIN puede gestionarlas',
  camerasCreateAction: 'Crear cámara',
  camerasEditAction: 'Editar cámara',
  camerasDeleteAction: 'Eliminar cámara',
  camerasViewAction: 'Ver cámara',
  camerasViewDisabledTooltip: 'Aún no está disponible para ver',
  camerasListTitle: 'Listado de cámaras',
  camerasListAria: 'Lista de cámaras registradas',
  camerasCountLabel: (count: number): string => `${count} cámara${count === 1 ? '' : 's'}`,
  camerasEmptyTitle: 'No hay cámaras registradas',
  camerasEmptyDescription: 'Cuando se creen cámaras aparecerán en esta lista',
  camerasLoadingData: 'Cargando cámaras...',
  camerasRefreshingData: 'Actualizando cámaras...',
  camerasErrorNetwork: 'No fue posible cargar cámaras. Verifica la conexión',
  camerasErrorBadRequest: 'Los parámetros o datos de cámara no son válidos',
  camerasErrorUnauthorized: 'Tu sesión ya no es válida. Inicia sesión de nuevo',
  camerasErrorForbidden: 'No tienes permisos para gestionar cámaras',
  camerasErrorNotFound: 'No se encontró la cámara solicitada',
  camerasErrorConflict: 'La cámara no se pudo guardar por un conflicto de datos',
  camerasErrorUnexpected: 'Ocurrió un error inesperado al gestionar cámaras',
  camerasPaginationAria: 'Paginación de cámaras',
  camerasPaginationPrevious: 'Anterior',
  camerasPaginationNext: 'Siguiente',
  camerasPaginationStatus: (page: number, totalPages: number, totalItems: number): string =>
    `Página ${page} de ${totalPages} · ${totalItems} cámara${totalItems === 1 ? '' : 's'}`,
  camerasRetryAction: 'Reintentar',
  camerasCreateFormTitle: 'Nueva cámara',
  camerasEditFormTitle: 'Editar cámara',
  camerasFormNameLabel: 'Nombre de cámara',
  camerasFormNamePlaceholder: 'Ejemplo: Cámara Sendero Alto',
  camerasFormAngleXYLabel: 'Ángulo XY',
  camerasFormAngleXZLabel: 'Ángulo XZ',
  camerasFormRegionLabel: 'Región',
  camerasFormRegionPlaceholder: 'Ejemplo: Zona Norte',
  camerasFormAddressLabel: 'Dirección',
  camerasFormAddressPlaceholder: 'Ejemplo: Sendero 4, km 2',
  camerasFormLatitudeLabel: 'Latitud',
  camerasFormLongitudeLabel: 'Longitud',
  camerasFormHeightLabel: 'Altura (m)',
  camerasFormRequiredField: 'Este campo es obligatorio',
  camerasFormAngleRange: 'Debe estar entre 0 y 360',
  camerasFormLatitudeRange: 'Debe estar entre -90 y 90',
  camerasFormLongitudeRange: 'Debe estar entre -180 y 180',
  camerasFormNumericInvalid: 'Ingresa un número válido',
  camerasFormSubmitCreate: 'Guardar cámara',
  camerasFormSubmitEdit: 'Guardar cambios',
  camerasFormCancel: 'Cancelar',
  camerasDeleteConfirm: '¿Seguro que deseas eliminar esta cámara?',
  camerasFormInvalid: 'Completa todos los campos con valores válidos',
  cameraDetailPageTitle: 'Detalle de camara | STDC',
  streamPageTitle: 'Streaming de camara | STDC',
  streamDummyPageTitle: 'Dummy Streaming | STDC',
  cameraDetailPlaceholderTitle: 'Detalle de camara en construccion',
  cameraDetailPlaceholderPrefix: 'Camara seleccionada:',
  cameraDetailUnknownCamera: 'Sin identificador',
  mapCameraPrefix: 'Camara',
  mapSocketConnectionError: 'No fue posible conectar con los sockets de monitoreo.',
  mapSocketDisconnected: 'Conexion en tiempo real desconectada. Mostrando ultimo estado.',
  streamViewerTitle: 'Streaming en vivo',
  streamSelectCamera: 'Cambiar camara',
  streamPreviousCamera: 'Camara anterior',
  streamNextCamera: 'Siguiente camara',
  streamSwitchUnavailable: 'No hay mas camaras disponibles',
  streamUnnamedCamera: 'Camara sin nombre',
  streamExit: 'Salir',
  streamReloadAction: 'Recargar',
  streamEnterFullscreen: 'Pantalla completa',
  streamExitFullscreen: 'Salir de pantalla completa',
  streamRotate: 'Rotar',
  streamConnectionError: 'No se pudo conectar al stream.',
  streamNoSignal: 'Sin senal de video en este momento.',
  streamSocketDisconnected: 'Socket desconectado',
  streamDelayLabel: (seconds: number): string => `Delay ${seconds}s`,
  streamBoundingBoxFallback: 'Ave',
  streamStateLoading: 'Conectando stream...',
  streamStateEmpty: 'Esperando datos de video...',
  streamStateLive: 'En vivo',
  streamStateError: 'Error de conexion',
  streamRetryLabel: (attempt: number): string => `Reintentando (${attempt})`,
  streamDummyHeading: 'Dummy de publicacion',
  streamDummyCameraId: 'Camera ID',
  streamDummyGenerateCameraId: 'Generar ID',
  streamDummyLatitude: 'Latitud',
  streamDummyLongitude: 'Longitud',
  streamDummyHeight: 'Altura (opcional)',
  streamDummyConnect: 'Conectar y publicar',
  streamDummyStop: 'Detener',
  streamDummyFramesSent: (count: number): string => `Frames enviados: ${count}`,
  streamDummyStatusConnected: 'Socket conectado',
  streamDummyStatusDisconnected: 'Socket desconectado',
  streamDummyInvalidCoordinates: 'Latitud y longitud son obligatorias.',
  streamDummyInvalidCoordinatesRange: 'Latitud y longitud deben estar dentro de Caldas.',
  streamDummyCameraSelectPlaceholder: 'Selecciona una camara disponible',
  streamDummyCameraOptionLabel: (name: string, id: string): string => `${name} (${id})`,
  streamDummyCoordinatesTooltip: (minLat: number, maxLat: number, minLng: number, maxLng: number): string =>
    `Caldas: latitud entre ${minLat} y ${maxLat}, longitud entre ${minLng} y ${maxLng}`,
  chatTitle: 'Tororoi Chat',
  chatLauncherOpenAria: 'Abrir Tororoi Chat',
  chatLauncherCloseAria: 'Cerrar Tororoi Chat',
  chatWindowAriaLabel: 'Ventana de Tororoi Chat',
  chatMessagesAriaLabel: 'Historial de mensajes de Tororoi Chat',
  chatInputLabel: 'Mensaje',
  chatInputPlaceholder: 'Escribe tu pregunta sobre aves...',
  chatSendButton: 'Enviar',
  chatInitialGreetingBold: '¡To-ro-rói!',
  chatInitialGreetingRest: ' Pregunta lo que quieras.',
  chatInitialBirdAlt: 'Tororoi saludando desde el chat',
  chatTypingStatus: 'Tororoi Chat está escribiendo',
  chatAssistantAvatarAlt: 'Avatar de Tororoi Chat',
  chatStandingBirdAlt: 'Tororoi de pie',
  chatStandingBirdHide: 'Ocultar Tororoi de pie',
  chatAssistantAvatarFallback: 'BH',
  chatLauncherPulseAria: 'Asistente Tororoi Chat disponible',
  chatMockResponseEmpty: 'Te leo. Cuando quieras, escribe tu pregunta y te ayudo.',
  chatMockResponseFirst: 'Perfecto, ya recibí tu consulta.',
  chatMockResponseSecond: 'Estoy analizando el contexto avícola de la zona.',
  chatMockResponseThird: 'Tengo una respuesta preliminar lista para ti.',
  chatMockResponseEcho: (message: string): string => `Mensaje detectado: ${message}.`,
  homeNavAriaLabel: 'Navegacion principal inferior',
  homeNavLabel: 'Inicio',
  settingsNavLabel: 'Ajustes',
  camerasNavLabel: 'Camaras',
  logoAlt: 'Logo de la app',
  passwordToggle: 'Mostrar u ocultar contraseña',
  usernameLabel: 'Nombre de usuario',
  usernamePlaceholder: 'Ingresa tu nombre de usuario',
  passwordLabel: 'Contraseña',
  passwordPlaceholder: 'Ingresa tu contraseña',
  passwordRulesPlaceholder: 'Al menos 8 caracteres',
  confirmPasswordLabel: 'Confirma tu contraseña',
  loginPageTitle: 'Inicia sesión | STDC',
  loginHeading: 'Inicia sesión',
  loginSubtitle: 'Observa, rastrea y descubre la fauna avícola de Caldas',
  loginSubmit: 'Iniciar sesión',
  loginFooterPrefix: '¿Eres nuevo?',
  loginFooterAction: 'Créate una cuenta',
  registerPageTitle: 'Regístrate | STDC',
  registerHeading: 'Regístrate',
  registerSubtitle: 'Crea tu cuenta y descubre más sobre la fauna avícola de nuestro departamento',
  registerSubmit: 'Crear cuenta',
  registerSubmitting: 'Creando cuenta...',
  loginSubmitting: 'Iniciando sesión...',
  registerFooterPrefix: '¿Ya tienes una cuenta?',
  registerFooterAction: 'Inicia sesión',
  authLoadingAria: 'Cargando sesión de usuario',
  authInvalidCredentials: 'Usuario o contraseña inválidos',
  authForbidden: 'El servidor rechazó la solicitud (forbidden)',
  authNetworkError: 'No fue posible conectar con el servidor',
  authUsernameTaken: 'El nombre de usuario ya existe',
  authValidationError: 'Los datos ingresados no son válidos',
  authUnexpectedError: 'Ocurrió un error inesperado. Intenta de nuevo',
  usernameRequired: 'El nombre de usuario es obligatorio',
  usernameMinLength: 'El nombre de usuario debe tener al menos 3 caracteres',
  passwordRequired: 'La contraseña es obligatoria',
  passwordMinLength: 'La contraseña debe tener al menos 8 caracteres',
  confirmPasswordRequired: 'Debes confirmar la contraseña',
  passwordMismatch: 'Las contraseñas no coinciden',
} as const

export type LabelKey = keyof typeof labels
