export const labels = {
  appTitle: 'STDC',
  homePageTitle: 'Inicio | STDC',
  homeLoaderAria: 'Cargando contenido de inicio',
  settingsPageTitle: 'Ajustes | STDC',
  settingsLoaderAria: 'Cargando contenido de ajustes',
  settingsHeading: 'Ajustes de cuenta',
  settingsProfileTitle: 'Información del usuario',
  settingsUsernameLabel: 'Usuario',
  settingsRoleLabel: 'Rol',
  settingsActionsTitle: 'Sesión',
  settingsLogoutButton: 'Cerrar sesión',
  roleAdministrator: 'Administrador',
  roleTourGuide: 'Guía turístico',
  authSessionExpired: 'Tu sesión expiró. Inicia sesión de nuevo',
  camerasPageTitle: 'Camaras | STDC',
  camerasLoaderAria: 'Cargando contenido de camaras',
  camerasManagementTitle: 'Gestión de cámaras',
  camerasAdminDescription: 'Puedes crear, editar o eliminar cámaras desde esta sección',
  camerasGuideDescription: 'Puedes visualizar cámaras, pero solo ADMIN puede gestionarlas',
  camerasCreateAction: 'Crear cámara',
  camerasEditAction: 'Editar cámara',
  camerasDeleteAction: 'Eliminar cámara',
  cameraDetailPageTitle: 'Detalle de camara | STDC',
  cameraDetailPlaceholderTitle: 'Detalle de camara en construccion',
  cameraDetailPlaceholderPrefix: 'Camara seleccionada:',
  cameraDetailUnknownCamera: 'Sin identificador',
  homeNavAriaLabel: 'Navegacion principal inferior',
  homeNavLabel: 'Inicio',
  settingsNavLabel: 'Ajustes',
  camerasNavLabel: 'Camaras',
  logoAlt: 'Logo de la app',
  passwordToggle: 'Mostrar u ocultar contraseña',
  usernameLabel: 'Nombre de usuario',
  usernamePlaceholder: 'Ingresa tu nombre de usuario',
  passwordLabel: 'Contraseña',
  passwordPlaceholder: 'Ingresa tu contraseña',
  passwordRulesPlaceholder: 'Al menos 8 caracteres',
  confirmPasswordLabel: 'Confirma tu contraseña',
  loginPageTitle: 'Inicia sesión | STDC',
  loginHeading: 'Inicia sesión',
  loginSubtitle: 'Observa, rastrea y descubre la fauna avícola de Caldas',
  loginSubmit: 'Iniciar sesión',
  loginFooterPrefix: '¿Eres nuevo?',
  loginFooterAction: 'Créate una cuenta',
  registerPageTitle: 'Regístrate | STDC',
  registerHeading: 'Regístrate',
  registerSubtitle: 'Crea tu cuenta y descubre más sobre la fauna avícola de nuestro departamento',
  registerSubmit: 'Crear cuenta',
  registerSubmitting: 'Creando cuenta...',
  loginSubmitting: 'Iniciando sesión...',
  registerFooterPrefix: '¿Ya tienes una cuenta?',
  registerFooterAction: 'Inicia sesión',
  authLoadingAria: 'Cargando sesión de usuario',
  authInvalidCredentials: 'Usuario o contraseña inválidos',
  authForbidden: 'El servidor rechazó la solicitud (forbidden)',
  authNetworkError: 'No fue posible conectar con el servidor',
  authUsernameTaken: 'El nombre de usuario ya existe',
  authUnexpectedError: 'Ocurrió un error inesperado. Intenta de nuevo',
  usernameRequired: 'El nombre de usuario es obligatorio',
  usernameMinLength: 'El nombre de usuario debe tener al menos 3 caracteres',
  passwordRequired: 'La contraseña es obligatoria',
  passwordMinLength: 'La contraseña debe tener al menos 8 caracteres',
  confirmPasswordRequired: 'Debes confirmar la contraseña',
  passwordMismatch: 'Las contraseñas no coinciden',
} as const

export type LabelKey = keyof typeof labels
