# ---------- Build stage ----------
FROM maven:3.9.9-eclipse-temurin-17 AS build

WORKDIR /build

# Copiar archivos de Maven primero (mejor cache)
COPY pom.xml .

RUN mvn -B -q -e -DskipTests dependency:go-offline

# Copiar el código fuente
COPY src ./src

# Compilar el proyecto
RUN mvn -B -DskipTests package


# ---------- Runtime stage ----------
FROM eclipse-temurin:17-jdk-jammy

WORKDIR /app

# Copiar el jar generado desde el stage anterior
COPY --from=build /build/target/*.jar app.jar

# Puerto típico de Spring Boot
EXPOSE 8080

# Ejecutar la aplicación
ENTRYPOINT ["java","-jar","app.jar"]