# Imagen base ligera
FROM python:3.12-slim

# Evita archivos .pyc y mejora logs
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Dependencias del sistema para compilar psycopg2 (pg_config)
RUN apt-get update && apt-get install -y --no-install-recommends \
	build-essential \
	libpq-dev \
	&& rm -rf /var/lib/apt/lists/*

# Instalar uv
RUN pip install --no-cache-dir uv

# Directorio de trabajo
WORKDIR /app

# Copiar archivos de dependencias primero (para cache de Docker)
COPY pyproject.toml uv.lock ./

# Instalar dependencias del proyecto
RUN uv sync --frozen --no-dev

# Copiar el resto del código
COPY . .

# Puerto usado por FastAPI
EXPOSE 8000

# Comando para ejecutar la API
CMD ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]